CREATE TABLE `products` ( 
    `id` INT NOT NULL AUTO_INCREMENT , 
    `no` VARCHAR(36) NOT NULL COMMENT '產品編號', 
    `name` VARCHAR(125) NOT NULL , 
    `brief` VARCHAR(255) NULL DEFAULT NULL COMMENT '簡述', 
    `desp` TEXT NULL DEFAULT NULL COMMENT '說明', 
    `qty` INT NOT NULL DEFAULT '0' , 
    `list_price` FLOAT NOT NULL COMMENT '定價', 
    `sale_price` FLOAT NOT NULL COMMENT '售價', 
    `is_off` TINYINT(1) NOT NULL DEFAULT '0' COMMENT '下架', 
    `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, 
    `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, 
    `deleted_at` TIMESTAMP NULL DEFAULT NULL , 
    PRIMARY KEY (`id`), UNIQUE (`no`)
) ENGINE = InnoDB;