# .gqlgen.yml example
#
# Refer to https://gqlgen.com/config/
# for detailed .gqlgen.yml documentation.

schema:
  - schemas/admin/**/*.graphql
  - schemas/models/**/*.graphql
exec:
  filename: build/gqlgen/admin/generated.go
  package: generated
model:
  filename: build/gqlgen/admin/models/models_gen.go
  package: models_gen
resolver:
  layout: follow-schema
  dir: app/graphql/admin/resolvers
  package: resolvers
autobind: []
