// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package models_gen

// The `File` type, represents the response of uploading a file.
type File struct {
	ID      int    `json:"id"`
	Name    string `json:"name"`
	Content string `json:"content"`
}

type NewTodo struct {
	Text   string `json:"text"`
	UserID string `json:"userId"`
}

type Todo struct {
	ID   string `json:"id"`
	Text string `json:"text"`
	Done bool   `json:"done"`
}
